# Generated by Django 3.2.7 on 2021-10-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='store',
            name='iban',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
