# Generated by Django 3.2.7 on 2021-10-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_iban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='friendly_name',
        ),
    ]
