# Generated by Django 3.2.7 on 2021-10-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_store_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
