# Generated by Django 3.2.7 on 2021-10-18 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_delete_sellerprofile'),
        ('store', '0007_store_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.userprofile'),
        ),
    ]
