# Generated by Django 3.2.7 on 2021-10-19 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.county'),
        ),
    ]
