# Generated by Django 3.2.7 on 2021-10-28 12:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_store_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='country',
            field=django_countries.fields.CountryField(default='Ireland', max_length=2),
        ),
    ]
