# Generated by Django 3.2.7 on 2021-09-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_town_or_city',
            new_name='default_town',
        ),
    ]
