# Generated by Django 3.2.7 on 2021-10-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_userprofile_is_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profile.userprofile')),
                ('organic', models.BooleanField(default=False)),
                ('seller_town', models.CharField(blank=True, max_length=40, null=True)),
                ('seller_county', models.CharField(blank=True, max_length=40, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
            bases=('profile.userprofile',),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_seller',
        ),
    ]
