# Generated by Django 3.2.7 on 2021-10-07 12:39

from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20211006_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default='', max_digits=3),
        ),
    ]
