# Generated by Django 3.2.7 on 2021-10-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20211007_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_county',
        ),
    ]
