# Generated by Django 3.2.7 on 2021-10-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_county'),
        ('profile', '0009_delete_sellerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='County',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_county',
            field=models.ForeignKey(default='limerick', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.county'),
        ),
    ]
