# Generated by Django 3.2.7 on 2021-10-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_alter_userprofile_default_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
