# Generated by Django 3.2.7 on 2021-10-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_store_user'),
        ('checkout', '0003_alter_order_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
        migrations.AddField(
            model_name='order',
            name='seller_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='store.store'),
        ),
    ]
