# Generated by Django 3.2.7 on 2021-10-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_county'),
        ('checkout', '0004_auto_20211009_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='store.store'),
        ),
    ]
