# Generated by Django 3.2.7 on 2021-09-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_userprofile_is_seller'),
        ('products', '0002_alter_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profile.userprofile'),
        ),
    ]
