# Generated by Django 3.2.7 on 2021-09-30 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_userprofile_is_seller'),
        ('products', '0003_product_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profile.userprofile'),
        ),
    ]
