# Generated by Django 3.2.7 on 2021-10-07 12:39

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211006_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
