# Generated by Django 3.2.7 on 2021-10-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_store_user'),
        ('products', '0008_auto_20211008_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='seller_store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
