# Generated by Django 3.2.7 on 2021-10-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_store_user'),
        ('products', '0009_auto_20211009_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
